server:
  port: 8001
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wyj
    password: 123
    #虚拟host 可以不设置,使用server默认host
    virtual-host: test_host1

    #使得消息中带 correlation_id,将发送的消息和返回值之间关联。
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)，开启发送失败退回
    publisher-returns: true
  data:
    mongodb:
      uri: mongodb://localhost/geo_data_hub_back_dev
